const sources = [
  {
    id: 'benedict-evans',
    name: 'Benedict Evans',
    subtitle: null,
    type: 'rss',
    feedUrl: 'https://www.ben-evans.com/benedictevans?format=rss',
    homepageUrl: 'https://www.ben-evans.com',
  },
  {
    id: 'stratechery',
    name: 'Ben Thompson',
    subtitle: 'Stratechery',
    type: 'rss',
    feedUrl: 'https://stratechery.com/feed/',
    homepageUrl: 'https://stratechery.com',
  },
  {
    id: 'scholars-stage',
    name: 'Tanner Greer',
    subtitle: "Scholar's Stage",
    type: 'rss',
    feedUrl: 'https://scholars-stage.org/feed/',
    homepageUrl: 'https://scholars-stage.org',
  },
  {
    id: 'the-diff',
    name: 'Byrne Hobart',
    subtitle: 'The Diff',
    type: 'rss',
    feedUrl: 'https://thediff.co/feed/',
    homepageUrl: 'https://thediff.co',
  },
  {
    id: 'eugene-wei',
    name: 'Eugene Wei',
    subtitle: 'Remains of the Day',
    type: 'rss',
    feedUrl: 'https://www.eugenewei.com/blog?format=rss',
    homepageUrl: 'https://www.eugenewei.com',
    fallbackFeedUrl: 'https://eugenewei.substack.com/feed',
  },
  {
    id: 'adam-tooze',
    name: 'Adam Tooze',
    subtitle: 'Chartbook',
    type: 'rss',
    feedUrl: 'https://adamtooze.substack.com/feed',
    homepageUrl: 'https://adamtooze.substack.com',
  },
  {
    id: 'bilahari-kausikan',
    name: 'Bilahari Kausikan',
    subtitle: null,
    type: 'google-news',
    searchQuery: '"Bilahari Kausikan"',
    homepageUrl: 'https://www.isas.nus.edu.sg/',
  },
  {
    id: 'kishore-mahbubani',
    name: 'Kishore Mahbubani',
    subtitle: null,
    type: 'google-news',
    searchQuery: '"Kishore Mahbubani"',
    homepageUrl: 'https://mahbubani.net',
  },
  {
    id: 'raja-mohan',
    name: 'C. Raja Mohan',
    subtitle: null,
    type: 'google-news',
    searchQuery: '"C. Raja Mohan"',
    homepageUrl: 'https://www.foreignaffairs.com/authors/c-raja-mohan',
  },
];

module.exports = sources;
